// Location data with associated graphics
const LOCATIONS = [
    { // Susan B. Anthony's Grave
        id: 0,
        name: "Stickered Sentinel",
        trueName: "Susan B. Anthony",
        lat: 43.1346,
        lng: -77.6156,
        //lat: 43.127,
        //lng: -77.613,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#FF5733",
        shape: "box",
        scale: "0.3 0.3 0.3",
        position: "0 0.5 0"
    },
    { // Sylvan Waters
        id: 1,
        name: "Quiet Pond",
        trueName: "Sylvan Waters",
        lat: 43.130,
        lng: -77.616,
        //lat: 43.127,
        //lng: -77.613,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#33FF57",
        shape: "sphere",
        scale: "0.4 0.4 0.4",
        position: "0 0.7 0"
    },
    { // Civil War Memorial
        id: 2,
        name: "Silent Regiment",
        trueName: "Civil War Memorial",
        lat: 43.129,
        lng: -77.624,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#3357FF",
        shape: "cylinder",
        scale: "0.3 0.5 0.3",
        position: "0 0.6 0"
    },
    { // Frederick Douglass' Grave
        id: 3,
        name: "Watcher on the Hill",
        trueName: "Frederick Douglass",
        lat: 43.131,
        lng: -77.614,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#F033FF",
        shape: "cone",
        scale: "0.4 0.6 0.4",
        position: "0 0.8 0"
    },
    { // Daffidel Project
        id: 4,
        name: "Blooming Hollow",
        trueName: "Daffodil Project",
        //lat: 43.130,
        //lng: -77.617,
        lat: 43.127,
        lng: -77.613,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#FF33F0",
        shape: "torus",
        scale: "0.4 0.4 0.4",
        position: "0 0.5 0"
    },
    { // Drummer Boy's Grave
        id: 5,
        name: "Drummer Boy's Grave",
        trueName: "Alexander Millener",
        lat: 43.125,
        lng: -77.619,
        radius: 100,
        completed: false,
        inProximity: false,
        color: "#33FFF0",
        shape: "octahedron",
        scale: "0.4 0.4 0.4",
        position: "0 0.5 0"
    }
];
